FROM php:7.4-fpm as fpm

# Aqui será colocado suas depedencias do php-fpm e aonde sera container

FROM nginx as nginx

# Aqui sera colocado seus codigos e configuracoes de projeto onde sera inicializado